name: Docket tags

on:
  push:
    branches: [master]
  release:
    types:
    - published

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    -
      name: docker-meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: |
          localhost:5000/myapp
          alice/myapp
          ghcr.io/alice/myapp
          
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=edge,branch=master
